# Generated by Django 3.2.16 on 2022-12-12 16:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128, verbose_name='Фамилия и имя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('desired_position', models.CharField(max_length=128, verbose_name='Желаемая должность')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Телефонный номер +7')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Ваши навыки')),
                ('education', models.TextField(blank=True, null=True, verbose_name='Ваше образование')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Ваш опыт')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
